/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`handle_deployment_logs_request`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HandleDeploymentLogsRequestError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`handle_deployment_status_request`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HandleDeploymentStatusRequestError {
    UnknownValue(serde_json::Value),
}


pub async fn handle_deployment_logs_request(configuration: &configuration::Configuration, organization: &str, cluster: Option<&str>, project: &str, environment: &str, version: Option<&str>) -> Result<String, Error<HandleDeploymentLogsRequestError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_organization = organization;
    let p_cluster = cluster;
    let p_project = project;
    let p_environment = environment;
    let p_version = version;

    let uri_str = format!("{}/deployment/logs", configuration.base_path, organization=crate::apis::urlencode(p_organization), cluster=crate::apis::urlencode(p_cluster.unwrap()), project=crate::apis::urlencode(p_project), environment=crate::apis::urlencode(p_environment), version=crate::apis::urlencode(p_version.unwrap()));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<HandleDeploymentLogsRequestError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn handle_deployment_status_request(configuration: &configuration::Configuration, organization: &str, cluster: Option<&str>, project: &str, environment: Option<&str>, version: Option<&str>) -> Result<String, Error<HandleDeploymentStatusRequestError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_organization = organization;
    let p_cluster = cluster;
    let p_project = project;
    let p_environment = environment;
    let p_version = version;

    let uri_str = format!("{}/deployment/status", configuration.base_path, organization=crate::apis::urlencode(p_organization), cluster=crate::apis::urlencode(p_cluster.unwrap()), project=crate::apis::urlencode(p_project), environment=crate::apis::urlencode(p_environment.unwrap()), version=crate::apis::urlencode(p_version.unwrap()));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<HandleDeploymentStatusRequestError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

