/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`handle_infra_logs_request`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HandleInfraLogsRequestError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`handle_service_logs_request`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HandleServiceLogsRequestError {
    UnknownValue(serde_json::Value),
}


pub async fn handle_infra_logs_request(configuration: &configuration::Configuration, organization: &str, cluster: &str, project: Option<&str>, environment: Option<&str>, service: Option<&str>, infra_component_type: &str) -> Result<models::ServiceInfraLogResponseDto, Error<HandleInfraLogsRequestError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_organization = organization;
    let p_cluster = cluster;
    let p_project = project;
    let p_environment = environment;
    let p_service = service;
    let p_infra_component_type = infra_component_type;

    let uri_str = format!("{}/infra/logs", configuration.base_path, organization=crate::apis::urlencode(p_organization), cluster=crate::apis::urlencode(p_cluster), project=crate::apis::urlencode(p_project.unwrap()), environment=crate::apis::urlencode(p_environment.unwrap()), service=crate::apis::urlencode(p_service.unwrap()), infra_component_type=crate::apis::urlencode(p_infra_component_type));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ServiceInfraLogResponseDto`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ServiceInfraLogResponseDto`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<HandleInfraLogsRequestError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn handle_service_logs_request(configuration: &configuration::Configuration, organization: &str, cluster: &str, project: &str, environment: &str, service: &str, pod_name: Option<&str>, deployment_id: Option<&str>) -> Result<models::ServiceLogResponseDto, Error<HandleServiceLogsRequestError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_organization = organization;
    let p_cluster = cluster;
    let p_project = project;
    let p_environment = environment;
    let p_service = service;
    let p_pod_name = pod_name;
    let p_deployment_id = deployment_id;

    let uri_str = format!("{}/service/logs", configuration.base_path, organization=crate::apis::urlencode(p_organization), cluster=crate::apis::urlencode(p_cluster), project=crate::apis::urlencode(p_project), environment=crate::apis::urlencode(p_environment), service=crate::apis::urlencode(p_service), pod_name=crate::apis::urlencode(p_pod_name.unwrap()), deployment_id=crate::apis::urlencode(p_deployment_id.unwrap()));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ServiceLogResponseDto`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ServiceLogResponseDto`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<HandleServiceLogsRequestError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

