/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`handle_shell_remote_debug`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HandleShellRemoteDebugError {
    UnknownValue(serde_json::Value),
}


pub async fn handle_shell_remote_debug(configuration: &configuration::Configuration, organization: &str, cluster: &str, flavor: models::DebugFlavor, tty_width: i32, tty_height: i32, node_selector: Option<&str>) -> Result<String, Error<HandleShellRemoteDebugError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_organization = organization;
    let p_cluster = cluster;
    let p_flavor = flavor;
    let p_tty_width = tty_width;
    let p_tty_height = tty_height;
    let p_node_selector = node_selector;

    let uri_str = format!("{}/shell/debug", configuration.base_path, organization=crate::apis::urlencode(p_organization), cluster=crate::apis::urlencode(p_cluster), flavor=p_flavor.to_string(), tty_width=p_tty_width, tty_height=p_tty_height, node_selector=crate::apis::urlencode(p_node_selector.unwrap()));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<HandleShellRemoteDebugError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

