/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`handle_shell_exec`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HandleShellExecError {
    UnknownValue(serde_json::Value),
}


pub async fn handle_shell_exec(configuration: &configuration::Configuration, organization: &str, cluster: &str, project: &str, environment: &str, service: &str, pod_name: Option<&str>, container_name: Option<&str>, command: Vec<String>, tty_width: i32, tty_height: i32) -> Result<String, Error<HandleShellExecError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_organization = organization;
    let p_cluster = cluster;
    let p_project = project;
    let p_environment = environment;
    let p_service = service;
    let p_pod_name = pod_name;
    let p_container_name = container_name;
    let p_command = command;
    let p_tty_width = tty_width;
    let p_tty_height = tty_height;

    let uri_str = format!("{}/shell/exec", configuration.base_path, organization=crate::apis::urlencode(p_organization), cluster=crate::apis::urlencode(p_cluster), project=crate::apis::urlencode(p_project), environment=crate::apis::urlencode(p_environment), service=crate::apis::urlencode(p_service), pod_name=crate::apis::urlencode(p_pod_name.unwrap()), container_name=crate::apis::urlencode(p_container_name.unwrap()), command=p_command.join(",").as_ref(), tty_width=p_tty_width, tty_height=p_tty_height);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<HandleShellExecError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

