/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationStatusDto {
    #[serde(rename = "certificates")]
    pub certificates: Vec<models::CertificateStatusDto>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "pods")]
    pub pods: Vec<models::PodStatusDto>,
    #[serde(rename = "scaled_object", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scaled_object: Option<Option<Box<models::ScaledObjectStatusDto>>>,
    #[serde(rename = "state")]
    pub state: models::ServiceStateDto,
}

impl ApplicationStatusDto {
    pub fn new(certificates: Vec<models::CertificateStatusDto>, id: String, pods: Vec<models::PodStatusDto>, state: models::ServiceStateDto) -> ApplicationStatusDto {
        ApplicationStatusDto {
            certificates,
            id,
            pods,
            scaled_object: None,
            state,
        }
    }
}

