/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArgocdAppStatusDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "pods")]
    pub pods: Vec<models::PodStatusDto>,
    #[serde(rename = "state")]
    pub state: models::ServiceStateDto,
}

impl ArgocdAppStatusDto {
    pub fn new(id: String, pods: Vec<models::PodStatusDto>, state: models::ServiceStateDto) -> ArgocdAppStatusDto {
        ArgocdAppStatusDto {
            id,
            pods,
            state,
        }
    }
}

