/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BlueprintServiceCreatedEvent : One blueprint service-created event. The stream emits these until the connection closes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlueprintServiceCreatedEvent {
    /// Id of the blueprint whose service was created.
    #[serde(rename = "blueprint_id")]
    pub blueprint_id: uuid::Uuid,
}

impl BlueprintServiceCreatedEvent {
    /// One blueprint service-created event. The stream emits these until the connection closes.
    pub fn new(blueprint_id: uuid::Uuid) -> BlueprintServiceCreatedEvent {
        BlueprintServiceCreatedEvent {
            blueprint_id,
        }
    }
}

