/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterQuotaWarningDto {
    #[serde(rename = "detected_at")]
    pub detected_at: i64,
    #[serde(rename = "last_seen_at")]
    pub last_seen_at: i64,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "quota_code")]
    pub quota_code: String,
    #[serde(rename = "quota_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quota_name: Option<Option<String>>,
    #[serde(rename = "region", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub region: Option<Option<String>>,
    #[serde(rename = "resource", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub resource: Option<Option<String>>,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "suggested_action")]
    pub suggested_action: String,
}

impl ClusterQuotaWarningDto {
    pub fn new(detected_at: i64, last_seen_at: i64, message: String, provider: String, quota_code: String, source: String, status: String, suggested_action: String) -> ClusterQuotaWarningDto {
        ClusterQuotaWarningDto {
            detected_at,
            last_seen_at,
            message,
            provider,
            quota_code,
            quota_name: None,
            region: None,
            resource: None,
            source,
            status,
            suggested_action,
        }
    }
}

