/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterMetricsDto {
    #[serde(rename = "node_pools")]
    pub node_pools: Vec<models::NodePoolInfoDto>,
    #[serde(rename = "nodes")]
    pub nodes: Vec<models::ClusterNodeDto>,
    #[serde(rename = "pvcs")]
    pub pvcs: Vec<models::PvcInfoDto>,
}

impl ClusterMetricsDto {
    pub fn new(node_pools: Vec<models::NodePoolInfoDto>, nodes: Vec<models::ClusterNodeDto>, pvcs: Vec<models::PvcInfoDto>) -> ClusterMetricsDto {
        ClusterMetricsDto {
            node_pools,
            nodes,
            pvcs,
        }
    }
}

