/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterListNodesResponseDto {
    #[serde(rename = "nodes")]
    pub nodes: Vec<models::NodeDto>,
}

impl ClusterListNodesResponseDto {
    pub fn new(nodes: Vec<models::NodeDto>) -> ClusterListNodesResponseDto {
        ClusterListNodesResponseDto {
            nodes,
        }
    }
}

