/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterStatusDto {
    #[serde(rename = "computed_status")]
    pub computed_status: Box<models::ClusterComputedStatusDto>,
    #[serde(rename = "tls_certificate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tls_certificate: Option<Option<Box<models::CertificateStatusDto>>>,
}

impl ClusterStatusDto {
    pub fn new(computed_status: models::ClusterComputedStatusDto) -> ClusterStatusDto {
        ClusterStatusDto {
            computed_status: Box::new(computed_status),
            tls_certificate: None,
        }
    }
}

