/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerStateTerminatedDto {
    #[serde(rename = "exit_code")]
    pub exit_code: i32,
    #[serde(rename = "exit_code_message")]
    pub exit_code_message: String,
    #[serde(rename = "finished_at")]
    pub finished_at: i64,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "signal")]
    pub signal: i32,
    #[serde(rename = "started_at")]
    pub started_at: i64,
}

impl ContainerStateTerminatedDto {
    pub fn new(exit_code: i32, exit_code_message: String, finished_at: i64, message: String, reason: String, signal: i32, started_at: i64) -> ContainerStateTerminatedDto {
        ContainerStateTerminatedDto {
            exit_code,
            exit_code_message,
            finished_at,
            message,
            reason,
            signal,
            started_at,
        }
    }
}

