/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DebugFlavor {
    #[serde(rename = "REGULAR_PRIVILEGE")]
    RegularPrivilege,
    #[serde(rename = "FULL_PRIVILEGE")]
    FullPrivilege,

}

impl std::fmt::Display for DebugFlavor {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RegularPrivilege => write!(f, "REGULAR_PRIVILEGE"),
            Self::FullPrivilege => write!(f, "FULL_PRIVILEGE"),
        }
    }
}

impl Default for DebugFlavor {
    fn default() -> DebugFlavor {
        Self::RegularPrivilege
    }
}

