/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KubeVersionStatusOkValue {
    #[serde(rename = "kube_version")]
    pub kube_version: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl KubeVersionStatusOkValue {
    pub fn new(kube_version: String, r#type: String) -> KubeVersionStatusOkValue {
        KubeVersionStatusOkValue {
            kube_version,
            r#type,
        }
    }
}

