/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetricDto {
    #[serde(rename = "current")]
    pub current: i32,
    #[serde(rename = "current_percent")]
    pub current_percent: i32,
    #[serde(rename = "limit")]
    pub limit: i32,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: models::ResourceStatusDto,
    #[serde(rename = "unit")]
    pub unit: models::UnitDto,
}

impl MetricDto {
    pub fn new(current: i32, current_percent: i32, limit: i32, status: models::ResourceStatusDto, unit: models::UnitDto) -> MetricDto {
        MetricDto {
            current,
            current_percent,
            limit,
            name: None,
            status,
            unit,
        }
    }
}

