/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetricsUsageDto {
    #[serde(rename = "cpu_milli_usage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cpu_milli_usage: Option<Option<i32>>,
    #[serde(rename = "cpu_percent_usage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cpu_percent_usage: Option<Option<i32>>,
    #[serde(rename = "disk_mib_usage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub disk_mib_usage: Option<Option<i32>>,
    #[serde(rename = "disk_percent_usage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub disk_percent_usage: Option<Option<i32>>,
    #[serde(rename = "memory_mib_rss_usage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub memory_mib_rss_usage: Option<Option<i32>>,
    #[serde(rename = "memory_mib_working_set_usage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub memory_mib_working_set_usage: Option<Option<i32>>,
    #[serde(rename = "memory_percent_rss_usage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub memory_percent_rss_usage: Option<Option<i32>>,
    #[serde(rename = "memory_percent_working_set_usage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub memory_percent_working_set_usage: Option<Option<i32>>,
}

impl MetricsUsageDto {
    pub fn new() -> MetricsUsageDto {
        MetricsUsageDto {
            cpu_milli_usage: None,
            cpu_percent_usage: None,
            disk_mib_usage: None,
            disk_percent_usage: None,
            memory_mib_rss_usage: None,
            memory_mib_working_set_usage: None,
            memory_percent_rss_usage: None,
            memory_percent_working_set_usage: None,
        }
    }
}

