/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MissingComponentValue {
    #[serde(rename = "component_name")]
    pub component_name: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl MissingComponentValue {
    pub fn new(component_name: String, r#type: String) -> MissingComponentValue {
        MissingComponentValue {
            component_name,
            r#type,
        }
    }
}

