/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeResourceDto {
    #[serde(rename = "cpu_milli")]
    pub cpu_milli: i64,
    #[serde(rename = "ephemeral_storage_mib")]
    pub ephemeral_storage_mib: i64,
    #[serde(rename = "memory_mib")]
    pub memory_mib: i64,
    #[serde(rename = "pods")]
    pub pods: i64,
}

impl NodeResourceDto {
    pub fn new(cpu_milli: i64, ephemeral_storage_mib: i64, memory_mib: i64, pods: i64) -> NodeResourceDto {
        NodeResourceDto {
            cpu_milli,
            ephemeral_storage_mib,
            memory_mib,
            pods,
        }
    }
}

