/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeTaintDto {
    #[serde(rename = "effect")]
    pub effect: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl NodeTaintDto {
    pub fn new(effect: String, key: String, value: String) -> NodeTaintDto {
        NodeTaintDto {
            effect,
            key,
            value,
        }
    }
}

