/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeConditionDto {
    #[serde(rename = "last_heartbeat_time")]
    pub last_heartbeat_time: i64,
    #[serde(rename = "last_transition_time")]
    pub last_transition_time: i64,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl NodeConditionDto {
    pub fn new(last_heartbeat_time: i64, last_transition_time: i64, message: String, reason: String, status: String, r#type: String) -> NodeConditionDto {
        NodeConditionDto {
            last_heartbeat_time,
            last_transition_time,
            message,
            reason,
            status,
            r#type,
        }
    }
}

