/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeResourceAllocatedDto {
    #[serde(rename = "cpu_milli")]
    pub cpu_milli: i32,
    #[serde(rename = "memory_mib")]
    pub memory_mib: i32,
}

impl NodeResourceAllocatedDto {
    pub fn new(cpu_milli: i32, memory_mib: i32) -> NodeResourceAllocatedDto {
        NodeResourceAllocatedDto {
            cpu_milli,
            memory_mib,
        }
    }
}

