/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeResourceAllocatedDto {
    #[serde(rename = "limit_cpu_milli", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub limit_cpu_milli: Option<Option<i32>>,
    #[serde(rename = "limit_memory_mib", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub limit_memory_mib: Option<Option<i32>>,
    #[serde(rename = "request_cpu_milli")]
    pub request_cpu_milli: i32,
    #[serde(rename = "request_memory_mib")]
    pub request_memory_mib: i32,
}

impl NodeResourceAllocatedDto {
    pub fn new(request_cpu_milli: i32, request_memory_mib: i32) -> NodeResourceAllocatedDto {
        NodeResourceAllocatedDto {
            limit_cpu_milli: None,
            limit_memory_mib: None,
            request_cpu_milli,
            request_memory_mib,
        }
    }
}

