/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeResourceAllocatedDto {
    #[serde(rename = "limit_cpu_milli")]
    pub limit_cpu_milli: i32,
    #[serde(rename = "limit_memory_mib")]
    pub limit_memory_mib: i32,
    #[serde(rename = "request_cpu_milli")]
    pub request_cpu_milli: i32,
    #[serde(rename = "request_memory_mib")]
    pub request_memory_mib: i32,
}

impl NodeResourceAllocatedDto {
    pub fn new(limit_cpu_milli: i32, limit_memory_mib: i32, request_cpu_milli: i32, request_memory_mib: i32) -> NodeResourceAllocatedDto {
        NodeResourceAllocatedDto {
            limit_cpu_milli,
            limit_memory_mib,
            request_cpu_milli,
            request_memory_mib,
        }
    }
}

