/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PodQoveryServiceInfoDto {
    #[serde(rename = "environment_id")]
    pub environment_id: String,
    #[serde(rename = "environment_name")]
    pub environment_name: String,
    #[serde(rename = "project_id")]
    pub project_id: String,
    #[serde(rename = "project_name")]
    pub project_name: String,
    #[serde(rename = "service_id")]
    pub service_id: String,
    #[serde(rename = "service_name")]
    pub service_name: String,
}

impl PodQoveryServiceInfoDto {
    pub fn new(environment_id: String, environment_name: String, project_id: String, project_name: String, service_id: String, service_name: String) -> PodQoveryServiceInfoDto {
        PodQoveryServiceInfoDto {
            environment_id,
            environment_name,
            project_id,
            project_name,
            service_id,
            service_name,
        }
    }
}

