/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PvcInfoDto {
    #[serde(rename = "created_at")]
    pub created_at: i64,
    #[serde(rename = "disk_mib_capacity")]
    pub disk_mib_capacity: i32,
    #[serde(rename = "disk_mib_usage")]
    pub disk_mib_usage: i32,
    #[serde(rename = "disk_percent_usage")]
    pub disk_percent_usage: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "namespace", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<Option<String>>,
    #[serde(rename = "pod_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pod_name: Option<Option<String>>,
    #[serde(rename = "qovery_service_info", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub qovery_service_info: Option<Option<Box<models::PodQoveryServiceInfoDto>>>,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
}

impl PvcInfoDto {
    pub fn new(created_at: i64, disk_mib_capacity: i32, disk_mib_usage: i32, disk_percent_usage: i32, name: String) -> PvcInfoDto {
        PvcInfoDto {
            created_at,
            disk_mib_capacity,
            disk_mib_usage,
            disk_percent_usage,
            name,
            namespace: None,
            pod_name: None,
            qovery_service_info: None,
            status: None,
        }
    }
}

