/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum QoveryComponentInFailure {
    #[serde(rename="POD_IN_ERROR")]
    PodInError(Box<models::PodInErrorValue>),
    #[serde(rename="MISSING_COMPONENT")]
    MissingComponent(Box<models::MissingComponentValue>),
}

impl Default for QoveryComponentInFailure {
    fn default() -> Self {
        Self::PodInError(Default::default())
    }
}


