/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QoveryComponentDto {
    #[serde(rename = "error_detail")]
    pub error_detail: Vec<models::QoveryComponentInFailure>,
    #[serde(rename = "images_version")]
    pub images_version: Vec<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "status")]
    pub status: models::QoveryComponentStatus,
}

impl QoveryComponentDto {
    pub fn new(error_detail: Vec<models::QoveryComponentInFailure>, images_version: Vec<String>, name: String, namespace: String, status: models::QoveryComponentStatus) -> QoveryComponentDto {
        QoveryComponentDto {
            error_detail,
            images_version,
            name,
            namespace,
            status,
        }
    }
}

