/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum QoveryClusterKubeVersionStatus {
    #[serde(rename="OK")]
    Ok(Box<models::KubeVersionStatusOkValue>),
    #[serde(rename="DRIFT")]
    Drift(Box<models::KubeVersionStatusDriftValue>),
    #[serde(rename="UNKNOWN")]
    Unknown(Box<models::KubeVersionStatusUnknownValue>),
}

impl Default for QoveryClusterKubeVersionStatus {
    fn default() -> Self {
        Self::Ok(Default::default())
    }
}


