/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QoveryNodeFailure {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "node_attributes")]
    pub node_attributes: Box<models::QoveryNodeAttributes>,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl QoveryNodeFailure {
    pub fn new(message: String, node_attributes: models::QoveryNodeAttributes, reason: String, r#type: String) -> QoveryNodeFailure {
        QoveryNodeFailure {
            message,
            node_attributes: Box::new(node_attributes),
            reason,
            r#type,
        }
    }
}

