/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QoveryComponentContainerStatusIssue {
    #[serde(rename = "level")]
    pub level: models::QoveryComponentContainerStatusLevel,
    #[serde(rename = "message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub message: Option<Option<String>>,
    #[serde(rename = "reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Option<String>>,
}

impl QoveryComponentContainerStatusIssue {
    pub fn new(level: models::QoveryComponentContainerStatusLevel) -> QoveryComponentContainerStatusIssue {
        QoveryComponentContainerStatusIssue {
            level,
            message: None,
            reason: None,
        }
    }
}

