/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QoveryComponentStatus {
    #[serde(rename = "RUNNING")]
    Running,
    #[serde(rename = "ERROR")]
    Error,

}

impl std::fmt::Display for QoveryComponentStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Running => write!(f, "RUNNING"),
            Self::Error => write!(f, "ERROR"),
        }
    }
}

impl Default for QoveryComponentStatus {
    fn default() -> QoveryComponentStatus {
        Self::Running
    }
}

