/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QoveryNodeAttributes {
    #[serde(rename = "node_pool_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub node_pool_name: Option<Option<String>>,
}

impl QoveryNodeAttributes {
    pub fn new() -> QoveryNodeAttributes {
        QoveryNodeAttributes {
            node_pool_name: None,
        }
    }
}

