/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScaleTargetGvkrDto {
    #[serde(rename = "group")]
    pub group: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "resource")]
    pub resource: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl ScaleTargetGvkrDto {
    pub fn new(group: String, kind: String, resource: String, version: String) -> ScaleTargetGvkrDto {
        ScaleTargetGvkrDto {
            group,
            kind,
            resource,
            version,
        }
    }
}

