/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScaledObjectHealthDto {
    #[serde(rename = "number_of_failures", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub number_of_failures: Option<Option<i32>>,
    #[serde(rename = "status")]
    pub status: String,
}

impl ScaledObjectHealthDto {
    pub fn new(status: String) -> ScaledObjectHealthDto {
        ScaledObjectHealthDto {
            number_of_failures: None,
            status,
        }
    }
}

