/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScaledObjectStatusDto {
    #[serde(rename = "authentications_types", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub authentications_types: Option<Option<String>>,
    #[serde(rename = "composite_scaler_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub composite_scaler_name: Option<Option<String>>,
    #[serde(rename = "conditions")]
    pub conditions: Vec<models::ScaledObjectConditionDto>,
    #[serde(rename = "external_metric_names")]
    pub external_metric_names: Vec<String>,
    #[serde(rename = "health")]
    pub health: std::collections::HashMap<String, models::ScaledObjectHealthDto>,
    #[serde(rename = "hpa_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub hpa_name: Option<Option<String>>,
    #[serde(rename = "last_active_time")]
    pub last_active_time: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "original_replica_count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub original_replica_count: Option<Option<i32>>,
    #[serde(rename = "paused_replica_count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub paused_replica_count: Option<Option<i32>>,
    #[serde(rename = "resource_metric_names")]
    pub resource_metric_names: Vec<String>,
    #[serde(rename = "scale_target_gvkr", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scale_target_gvkr: Option<Option<Box<models::ScaleTargetGvkrDto>>>,
    #[serde(rename = "scale_target_kind", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scale_target_kind: Option<Option<String>>,
    #[serde(rename = "triggers_types", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub triggers_types: Option<Option<String>>,
}

impl ScaledObjectStatusDto {
    pub fn new(conditions: Vec<models::ScaledObjectConditionDto>, external_metric_names: Vec<String>, health: std::collections::HashMap<String, models::ScaledObjectHealthDto>, last_active_time: i64, name: String, resource_metric_names: Vec<String>) -> ScaledObjectStatusDto {
        ScaledObjectStatusDto {
            authentications_types: None,
            composite_scaler_name: None,
            conditions,
            external_metric_names,
            health,
            hpa_name: None,
            last_active_time,
            name,
            original_replica_count: None,
            paused_replica_count: None,
            resource_metric_names,
            scale_target_gvkr: None,
            scale_target_kind: None,
            triggers_types: None,
        }
    }
}

