/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceLogResponseDto {
    #[serde(rename = "container_name")]
    pub container_name: String,
    #[serde(rename = "created_at")]
    pub created_at: i64,
    #[serde(rename = "labels")]
    pub labels: std::collections::HashMap<String, String>,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "pod_name")]
    pub pod_name: String,
    #[serde(rename = "severity_text")]
    pub severity_text: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl ServiceLogResponseDto {
    pub fn new(container_name: String, created_at: i64, labels: std::collections::HashMap<String, String>, message: String, pod_name: String, severity_text: String, version: String) -> ServiceLogResponseDto {
        ServiceLogResponseDto {
            container_name,
            created_at,
            labels,
            message,
            pod_name,
            severity_text,
            version,
        }
    }
}

