/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceActionDetailsDto {
    #[serde(rename = "action")]
    pub action: models::ServiceActionDto,
    #[serde(rename = "sub_action")]
    pub sub_action: models::ServiceSubActionDto,
}

impl ServiceActionDetailsDto {
    pub fn new(action: models::ServiceActionDto, sub_action: models::ServiceSubActionDto) -> ServiceActionDetailsDto {
        ServiceActionDetailsDto {
            action,
            sub_action,
        }
    }
}

