/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceMetricsDto {
    #[serde(rename = "cpu")]
    pub cpu: Box<models::MetricDto>,
    #[serde(rename = "memory")]
    pub memory: Box<models::MetricDto>,
    #[serde(rename = "pod_name")]
    pub pod_name: String,
    #[serde(rename = "storages")]
    pub storages: Vec<models::MetricDto>,
}

impl ServiceMetricsDto {
    pub fn new(cpu: models::MetricDto, memory: models::MetricDto, pod_name: String, storages: Vec<models::MetricDto>) -> ServiceMetricsDto {
        ServiceMetricsDto {
            cpu: Box::new(cpu),
            memory: Box::new(memory),
            pod_name,
            storages,
        }
    }
}

