/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceInfraLogResponseDto {
    #[serde(rename = "created_at")]
    pub created_at: i64,
    #[serde(rename = "message")]
    pub message: String,
}

impl ServiceInfraLogResponseDto {
    pub fn new(created_at: i64, message: String) -> ServiceInfraLogResponseDto {
        ServiceInfraLogResponseDto {
            created_at,
            message,
        }
    }
}

