/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceMetricsV2Dto {
    #[serde(rename = "pods")]
    pub pods: Vec<models::PodInfoDto>,
    #[serde(rename = "pvcs")]
    pub pvcs: Vec<models::PvcInfoDto>,
}

impl ServiceMetricsV2Dto {
    pub fn new(pods: Vec<models::PodInfoDto>, pvcs: Vec<models::PvcInfoDto>) -> ServiceMetricsV2Dto {
        ServiceMetricsV2Dto {
            pods,
            pvcs,
        }
    }
}

