/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TerraformStatusDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "pods")]
    pub pods: Vec<models::PodStatusDto>,
    #[serde(rename = "state")]
    pub state: models::ServiceStateDto,
    #[serde(rename = "triggered_action")]
    pub triggered_action: Box<models::ServiceActionDetailsDto>,
}

impl TerraformStatusDto {
    pub fn new(id: String, pods: Vec<models::PodStatusDto>, state: models::ServiceStateDto, triggered_action: models::ServiceActionDetailsDto) -> TerraformStatusDto {
        TerraformStatusDto {
            id,
            pods,
            state,
            triggered_action: Box::new(triggered_action),
        }
    }
}

