/*
 * websocket-gateway
 *
 * Describe the websocket endpoints of Qovery
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: erebe@erebe.eu
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnitDto {
    #[serde(rename = "mCPU")]
    MCpu,
    #[serde(rename = "MiB")]
    MiB,
    #[serde(rename = "GiB")]
    GiB,

}

impl std::fmt::Display for UnitDto {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MCpu => write!(f, "mCPU"),
            Self::MiB => write!(f, "MiB"),
            Self::GiB => write!(f, "GiB"),
        }
    }
}

impl Default for UnitDto {
    fn default() -> UnitDto {
        Self::MCpu
    }
}

